### PR TITLE
Support pydantic v2

### PR DESCRIPTION
**Pull request by tefra**
## 📒 Description

The goal is to add support for pydantic v2 models.

 - [x] Update filters to generate pydantic BaseModel subsclasses
 - [x] Update Compat layer
 - [x] Update fixtures
 - [x] Pass all the sample suites

## 🔗 What I've Done

> Write a description of the steps taken to resolve the issue

## 💬 Comments

> A place to write any comments to the reviewer.
>

## 🛫 Checklist

- [ ] Updated docs
- [ ] Added unit-tests

### CODE REVIEW

**Comment by fleimgruber** [comment]
@tefra any plans on continuing this effort? Could you give me a rough idea of status and missing pieces then I can have a look and eventually a shot at this.

**Comment by tefra** [comment]
> @tefra any plans on continuing this effort? Could you give me a rough idea of status and missing pieces then I can have a look and eventually have a shot at this.

I am so unbelievably stretched, honestly @fleimgruber I don't know, for the next couple of months I don't see how. Even then pydantic moves so fast this project is really doomed, I should admit defeat and simply shut it down.

**Comment by fleimgruber** [comment]
Thanks for checking back and your honesty. Maybe pydantic stabilizes at some point and then this can be picked up again - I think this project is a good idea!

**Comment by tefra** [comment]
Pydantic has locked us out, there is no way to add additional metadata per field, the extras are deprecated and the json_schema_extra expects json values...


Creating true pydantic models, is impossible back to pydantic dataclasses

**Pull request merged**
